name: Build Jekyll and Deploy to Firebase

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
  schedule:
  - cron: "0 2 * * *"

env:
  JEKYLL_ENV: production
  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache Bundler 💾
      uses: actions/cache@v2
      with:
        path: ~/.firebase, ~/.jekyll-cache, ~/vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Use Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Build 🏗
      run: bundle exec jekyll build --trace

    - name: Deploy to Firebase
      if: github.ref == 'refs/heads/master'
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLOUDNATIVE_EU }}'
        channelId: live
        projectId: cloudnative-eu

    - name: Deploy Preview to Firebase
      if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLOUDNATIVE_EU }}'
        projectId: cloudnative-eu